<a href="https://colab.research.google.com/github/ColeJ1115/NYC-Travel/blob/main/NYC_Analysis_Data_Cleaning_Part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Day 2 of Data Cleaning**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dbnb  = pd.read_csv('Airbnb_Cleaned.csv')

In [ ]:
dbnb

,Unnamed: 0,neighbourhood_group,room_type,price,minimum_nights,availability_365
0,0,Brooklyn,Private room,149,1,365
1,1,Manhattan,Entire home/apt,225,1,355
2,2,Manhattan,Private room,150,3,365
3,3,Brooklyn,Entire home/apt,89,1,194
4,4,Manhattan,Entire home/apt,80,10,0
...,...,...,...,...,...,...
48890,48890,Brooklyn,Private room,70,2,9
48891,48891,Brooklyn,Private room,40,4,36
48892,48892,Manhattan,Entire home/apt,115,10,27
48893,48893,Manhattan,Shared room,55,1,2
48894,48894,Manhattan,Private room,90,7,23

In [ ]:
dbnb.groupby('neighbourhood_group')['price'].mean()

neighbourhood_group
Bronx             87.496792
Brooklyn         124.383207
Manhattan        196.875814
Queens            99.517649
Staten Island    114.812332
Name: price, dtype: float64

In [ ]:
dbnb.groupby('neighbourhood_group')['minimum_nights'].mean()

neighbourhood_group
Bronx            4.560953
Brooklyn         6.056556
Manhattan        8.579151
Queens           5.181433
Staten Island    4.831099
Name: minimum_nights, dtype: float64

In [ ]:
dbnb['total_cost'] = dbnb['price'] * dbnb['minimum_nights']

In [ ]:
dbnb.groupby('neighbourhood_group')['total_cost'].mean()

neighbourhood_group
Bronx             346.841430
Brooklyn          806.924343
Manhattan        1890.080283
Queens            893.319802
Staten Island     533.378016
Name: total_cost, dtype: float64

In [ ]:
dair = dbnb.groupby('neighbourhood_group')

Grouping Airbnb dataset by "nieghborhood group" showcasing price, required minimum nights, and availability. Created "total_cost" column by multiplying price by minimum_nights columns. Can group by neighborhood to find average cost and minimum nights need for each neighborhood.

In [ ]:
dair.head()

,Unnamed: 0,neighbourhood_group,room_type,price,minimum_nights,availability_365,total_cost
0,0,Brooklyn,Private room,149,1,365,149
1,1,Manhattan,Entire home/apt,225,1,355,225
2,2,Manhattan,Private room,150,3,365,450
3,3,Brooklyn,Entire home/apt,89,1,194,89
4,4,Manhattan,Entire home/apt,80,10,0,800
5,5,Manhattan,Entire home/apt,200,3,129,600
6,6,Brooklyn,Private room,60,45,0,2700
7,7,Manhattan,Private room,79,2,220,158
12,12,Brooklyn,Private room,89,4,314,356
15,15,Brooklyn,Entire home/apt,140,2,46,280
46,46,Queens,Private room,130,3,215,390
77,77,Queens,Private room,70,30,324,2100
143,143,Queens,Private room,140,2,1,280
161,161,Queens,Private room,79,30,126,2370
169,169,Staten Island,Private room,70,2,312,140
171,171,Bronx,Private room,40,1,353,40
181,181,Queens,Entire home/apt,350,8,365,2800
207,207,Bronx,Private room,45,1,323,45
249,249,Staten Island,Private room,36,2,360,72
250,250,Staten Island,Private room,37,2,0,74
251,251,Staten Island,Private room,37,2,320,74
256,256,Staten Island,Private room,36,2,340,72
260,260,Bronx,Private room,90,2,349,180
261,261,Bronx,Entire home/apt,105,2,365,210
309,309,Bronx,Entire home/apt,90,30,346,2700

In [ ]:
dline = pd.read_csv('Airline_Cleaned.csv')

In [ ]:
dline.head()

,Unnamed: 0,Age,Airport Name,Airport Country Code,Country Name,Departure Date,Arrival Airport,Month_Year
0,1214,42,John F Kennedy International Airport,US,United States,2022-03-11,JFK,2022-03-01
1,10667,65,La Guardia Airport,US,United States,2022-12-18,LGA,2022-12-01
2,11091,49,Flushing Airport,US,United States,2022-06-07,FLU,2022-06-01
3,12102,65,John F Kennedy International Airport,US,United States,2022-10-15,JFK,2022-10-01
4,13269,16,Flushing Airport,US,United States,2022-05-19,FLU,2022-05-01

In [ ]:
dpop = pd.read_csv('Population_Cleaned.csv')

This data will display population in New York, New York. We can use this to compare any relationship with Airbnb prices. Fully filtered down

In [ ]:
dpop.head()

,Unnamed: 0,NAME,STNAME,ESTIMATESBASE2020,POPESTIMATE2020,POPESTIMATE2021,POPESTIMATE2022,POPESTIMATE2023
0,46169,New York,New York,20202320,20104710,19854526,19673200,19571216

In [ ]:
dweather = pd.read_csv('Weather_Cleaned.csv')

In [ ]:
dweather.head()

,Unnamed: 0,Type,Severity,StartTime(UTC),EndTime(UTC),Precipitation(in),AirportCode,City,State
0,1003661,Fog,Moderate,2022-01-01 01:51:00,2022-01-01 02:51:00,0.00,KNYC,New York,NY
1,1003662,Rain,Light,2022-01-01 08:51:00,2022-01-01 09:51:00,0.00,KNYC,New York,NY
2,1003663,Rain,Light,2022-01-01 10:51:00,2022-01-01 19:51:00,0.25,KNYC,New York,NY
3,1003664,Rain,Light,2022-01-01 21:51:00,2022-01-02 02:41:00,0.47,KNYC,New York,NY
4,1003665,Rain,Moderate,2022-01-02 02:41:00,2022-01-02 04:22:00,1.07,KNYC,New York,NY

In [ ]:
dweather = dweather.drop(columns= ['EndTime(UTC)'])

In [ ]:
import datetime as dt

In [ ]:
dweather['Start_Time'] = pd.to_datetime(dweather['StartTime(UTC)']).dt.date

In [ ]:
dweather.head()

,Unnamed: 0,Type,Severity,StartTime(UTC),Precipitation(in),AirportCode,City,State,Start_Time
0,1003661,Fog,Moderate,2022-01-01 01:51:00,0.00,KNYC,New York,NY,2022-01-01
1,1003662,Rain,Light,2022-01-01 08:51:00,0.00,KNYC,New York,NY,2022-01-01
2,1003663,Rain,Light,2022-01-01 10:51:00,0.25,KNYC,New York,NY,2022-01-01
3,1003664,Rain,Light,2022-01-01 21:51:00,0.47,KNYC,New York,NY,2022-01-01
4,1003665,Rain,Moderate,2022-01-02 02:41:00,1.07,KNYC,New York,NY,2022-01-02

In [ ]:
dweather = dweather.drop(columns= ['StartTime(UTC)'])

In [ ]:
dweather.groupby('Start_Time')['Severity'].count()

Start_Time
2022-01-01     8
2022-01-02    14
2022-01-05     8
2022-01-07    22
2022-01-09     4
              ..
2022-12-16     8
2022-12-22     4
2022-12-23    20
2022-12-28     2
2022-12-31    14
Name: Severity, Length: 157, dtype: int64

In [ ]:
dweather['Month'] = pd.DatetimeIndex(dweather['Start_Time']).month

Filtering weather data most common weather types by month

In [ ]:
dweather.groupby('Month')['Type'].max()

Month
1     Snow
2     Snow
3     Snow
4     Rain
5     Rain
6     Rain
7     Rain
8     Rain
9     Rain
10    Rain
11    Rain
12    Snow
Name: Type, dtype: object

Total sum of precipitation in inches by month

In [ ]:
dweather.groupby('Month')['Precipitation(in)'].sum()

Month
1     15.18
2      7.60
3     11.20
4     17.56
5     18.32
6     15.26
7     29.88
8      9.24
9     19.32
10    21.80
11    15.20
12    25.66
Name: Precipitation(in), dtype: float64

In [ ]:
dweather.to_csv('Weather_Grouped.csv')

In [ ]:
dhotel = pd.read_csv('Hotel Prices.csv')

In [ ]:
dhotel.head()

         Series ID  Year Period     Label    Value  1-Month % Change
0  PCU721110721110  2022    M01  2022 Jan  152.252              -1.9
1  PCU721110721110  2022    M02  2022 Feb  154.947               1.8
2  PCU721110721110  2022    M03  2022 Mar  173.270              11.8
3  PCU721110721110  2022    M04  2022 Apr  165.921              -4.2
4  PCU721110721110  2022    M05  2022 May  162.905              -1.8

In [ ]:
dhotel.groupby('Period')['Value'].mean()

Period
M01    159.784667
M02    162.083667
M03    174.155667
M04    171.348000
M05    167.523333
M06    178.477000
M07    180.035000
M08    173.212000
M09    168.236500
M10    170.427500
M11    167.556000
M12    167.209500
Name: Value, dtype: float64

NYC has an averaged 8% price increase over the national average from online research. This column creates an estimate of NYC price.

In [ ]:
dhotel['NYC Avg'] = dhotel['Value'] * 1.08

In [ ]:
dhotel.head()

,Series ID,Year,Period,Label,Value,1-Month % Change,NYC Avg
0,PCU721110721110,2022,M01,2022 Jan,152.252,-1.9,164.43216
1,PCU721110721110,2022,M02,2022 Feb,154.947,1.8,167.34276
2,PCU721110721110,2022,M03,2022 Mar,173.270,11.8,187.13160
3,PCU721110721110,2022,M04,2022 Apr,165.921,-4.2,179.19468
4,PCU721110721110,2022,M05,2022 May,162.905,-1.8,175.93740

In [ ]:
dhotel.to_csv('Hotel_Grouped.csv')